<a href="https://colab.research.google.com/github/mahamtaqi3-cloud/Python-libraries-teaching-materials/blob/main/Introduction_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🐼 Introduction to Pandas: Importing CSVs & Exploring a Dataset

Pandas is a Python library used for loading, cleaning, analyzing, and manipulating structured data. In bioinformatics and biological research, it is useful for working with datasets containing genes, species, samples, environmental variables, experimental results, etc.

df = data frame
Its a variable that usually stands for Dataframe in pandas

In [ ]:
#1. Import Pandas
import pandas as pd

2. Import a CSV file

Suppose you have a file called plant_growth_biological_practice.csv:

In [ ]:
#df.head means display the first rows of a Dataframe

In [ ]:
import pandas as pd

df = pd.read_csv("plant_growth_biological_practice.csv")

df.head()

,Species,Temperature_C,Rainfall_mm,Soil_pH,Nitrogen_mg_kg,Growth_cm,Disease_Score,Leaf_Count
0,Wheat,22,110,6.5,45,14.2,1,8
1,Rice,28,150,6.2,52,18.5,2,10
2,Maize,30,90,6.8,60,21.0,1,12
3,Barley,20,100,6.7,40,12.8,0,7
4,Wheat,25,120,6.4,48,16.1,1,9

In [ ]:
#3. View the first rows
df.head()

,Species,Temperature_C,Rainfall_mm,Soil_pH,Nitrogen_mg_kg,Growth_cm,Disease_Score,Leaf_Count
0,Wheat,22,110,6.5,45,14.2,1,8
1,Rice,28,150,6.2,52,18.5,2,10
2,Maize,30,90,6.8,60,21.0,1,12
3,Barley,20,100,6.7,40,12.8,0,7
4,Wheat,25,120,6.4,48,16.1,1,9

In [ ]:
#You can specify the number:
df.head(3)

,Species,Temperature_C,Rainfall_mm,Soil_pH,Nitrogen_mg_kg,Growth_cm,Disease_Score,Leaf_Count
0,Wheat,22,110,6.5,45,14.2,1,8
1,Rice,28,150,6.2,52,18.5,2,10
2,Maize,30,90,6.8,60,21.0,1,12

In [ ]:
#4. View the last rows
df.tail()

,Species,Temperature_C,Rainfall_mm,Soil_pH,Nitrogen_mg_kg,Growth_cm,Disease_Score,Leaf_Count
15,Barley,18,110,6.7,41,12.2,0,7
16,Wheat,27,135,6.4,49,17.0,1,10
17,Rice,28,140,6.1,58,19.8,1,11
18,Maize,33,75,6.9,67,24.1,3,14
19,Barley,22,120,6.6,44,14.0,1,8

In [ ]:
#5. Check the dataset size
df.shape

(20, 8)

In [ ]:
#6. See column names
df.columns

Index(['Species', 'Temperature_C', 'Rainfall_mm', 'Soil_pH', 'Nitrogen_mg_kg',
       'Growth_cm', 'Disease_Score', 'Leaf_Count'],
      dtype='object')

In [ ]:
#7. Check data types
df.dtypes

Species            object
Temperature_C       int64
Rainfall_mm         int64
Soil_pH           float64
Nitrogen_mg_kg      int64
Growth_cm         float64
Disease_Score       int64
Leaf_Count          int64
dtype: object

In [ ]:
#8. Get basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Species         20 non-null     object
 1   Temperature_C   20 non-null     int64
 2   Rainfall_mm     20 non-null     int64
 3   Soil_pH         20 non-null     float64
 4   Nitrogen_mg_kg  20 non-null     int64
 5   Growth_cm       20 non-null     float64
 6   Disease_Score   20 non-null     int64
 7   Leaf_Count      20 non-null     int64
dtypes: float64(2), int64(5), object(1)
memory usage: 1.4+ KB

This is one of the most useful commands when you first receive a dataset. It tells you:



Number of rows
Column names
Missing values
Data types
Memory usage

In [ ]:
#9. Get statistical summary
df.describe()

,Temperature_C,Rainfall_mm,Soil_pH,Nitrogen_mg_kg,Growth_cm,Disease_Score,Leaf_Count
count,20.000000,20.00000,20.000000,20.000000,20.00000,20.000000,20.000000
mean,25.750000,117.25000,6.515000,51.750000,17.55500,1.350000,9.950000
std,4.470665,25.31252,0.296071,8.680741,3.82959,0.988087,2.258901
min,18.000000,75.00000,6.000000,38.000000,11.90000,0.000000,7.000000
25%,22.000000,98.75000,6.275000,44.750000,14.15000,1.000000,8.000000
50%,26.500000,117.50000,6.550000,51.000000,17.75000,1.000000,10.000000
75%,29.250000,136.25000,6.725000,58.500000,20.32500,2.000000,11.250000
max,33.000000,160.00000,7.000000,67.000000,24.10000,3.000000,14.000000

For numerical columns, Pandas gives:

Count
Mean
Standard deviation
Minimum
25th percentile
Median
75th percentile
Maximum

For example
Temperature    Rainfall    Growth
count          500         500
mean            25.4       124.6
min             18.0        50.0
max             35.0       200.0

In [ ]:
#10. Select a column
df["Leaf_Count"]

0      8
1     10
2     12
3      7
4      9
5     11
6     13
7      7
8      9
9     11
10    14
11     8
12     8
13    10
14    12
15     7
16    10
17    11
18    14
19     8
Name: Leaf_Count, dtype: int64

In [ ]:
#Or multiple columns:
df[["Temperature_C", "Rainfall_mm", "Growth_cm"]]

    Temperature_C  Rainfall_mm  Growth_cm
0              22          110       14.2
1              28          150       18.5
2              30           90       21.0
3              20          100       12.8
4              25          120       16.1
5              27          160       19.3
6              31           85       22.4
7              19          105       11.9
8              24          130       15.6
9              29          145       20.1
10             32           95       23.0
11             21          115       13.5
12             23          125       15.0
13             26          155       18.9
14             30           80       21.7
15             18          110       12.2
16             27          135       17.0
17             28          140       19.8
18             33           75       24.1
19             22          120       14.0

In [ ]:
#11. Check missing values
df.isnull().sum()

Species           0
Temperature_C     0
Rainfall_mm       0
Soil_pH           0
Nitrogen_mg_kg    0
Growth_cm         0
Disease_Score     0
Leaf_Count        0
dtype: int64

In [ ]:
#12. Find unique values
df["Species"].unique()

array(['Wheat', 'Rice', 'Maize', 'Barley'], dtype=object)

In [ ]:
#To count them:
df["Species"].nunique()

4

🧬 Biological Example

Imagine you have a dataset of plant growth:

In [ ]:
import pandas as pd

df = pd.read_csv("plant_growth_biological_practice.csv")

print(df.head())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
print(df.isnull().sum())

  Species  Temperature_C  Rainfall_mm  Soil_pH  Nitrogen_mg_kg  Growth_cm  \
0   Wheat             22          110      6.5              45       14.2
1    Rice             28          150      6.2              52       18.5
2   Maize             30           90      6.8              60       21.0
3  Barley             20          100      6.7              40       12.8
4   Wheat             25          120      6.4              48       16.1

   Disease_Score  Leaf_Count
0              1           8
1              2          10
2              1          12
3              0           7
4              1           9
(20, 8)
Index(['Species', 'Temperature_C', 'Rainfall_mm', 'Soil_pH', 'Nitrogen_mg_kg',
       'Growth_cm', 'Disease_Score', 'Leaf_Count'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Species         20 non-null     object
 1   Temperature_C   20 non-null     int64
 2   Rainfall_mm     20 non-null     int64
 3   Soil_pH         20 non-null     float64
 4   Nitrogen_mg_kg  20 non-null     int64
 5   Growth_cm       20 non-null     float64
 6   Disease_Score   20 non-null     int64
 7   Leaf_Count      20 non-null     int64
dtypes: float64(2), int64(5), object(1)
memory usage: 1.4+ KB
None
       Temperature_C  Rainfall_mm    Soil_pH  Nitrogen_mg_kg  Growth_cm  \
count      20.000000     20.00000  20.000000       20.000000   20.00000
mean       25.750000    117.25000   6.515000       51.750000   17.55500
std         4.470665     25.31252   0.296071        8.680741    3.82959
min        18.000000     75.00000   6.000000       38.000000   11.90000
25%        22.000000     98.75000   6.275000       44.750000   14.15000
50%        26.500000    117.50000   6.550000       51.000000   17.75000
75%        29.250000    136.25000   6.725000       58.500000   20.32500
max        33.000000    160.00000   7.000000       67.000000   24.10000

       Disease_Score  Leaf_Count
count      20.000000   20.000000
mean        1.350000    9.950000
std         0.988087    2.258901
min         0.000000    7.000000
25%         1.000000    8.000000
50%         1.000000   10.000000
75%         2.000000   11.250000
max         3.000000   14.000000
Species           0
Temperature_C     0
Rainfall_mm       0
Soil_pH           0
Nitrogen_mg_kg    0
Growth_cm         0
Disease_Score     0
Leaf_Count        0
dtype: int64

You could then investigate questions such as:

Does temperature affect plant growth?

For example:

df[["Temperature", "Growth"]]

Later, you could use Pandas together with NumPy, Matplotlib, Seaborn, and Scikit-learn to visualize the relationship and build a machine-learning model.

🔑 The basic Pandas workflow

CSV file → read_csv() → DataFrame → head() → shape → info() → describe() → check missing values → analyze

This is usually the first step in a data-analysis or machine-learning project.

##Practice questions

1) Create a CSV file in Excel and named employees.csv

 like this Employee Department Age Salary
  Save it as CSV file

(a) Read
(b) Display
(c) Find rows and columns
(d) Display the names of all columns
(e) Show information about the Dataframe using info()
(f) Display only Employee and Salary columns
(g) Calculate the average salary
(h) Find the maximum salary
(i) Find the minimum salary